development:
  adapter: postgresql
  encoding: utf8
  database: ecejpro_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  database: ecejpro_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: ecejpro_production
  pool: 5
