development:
  adapter: postgresql
  encoding: utf8
  database: sec_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  database: sec_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: sec_production
  pool: 5
